import "server-only";
import ExcelJS from "exceljs";
import { z } from "zod";
import { TEMPLATE_VERSION, type TemplateBusiness } from "./template";
export type ParsedRow={row:number;sku:string;name:string;unitsPerCarton?:number;cartons?:number;loose?:number;quantity:number;businessDate:string;supplierCode?:string;note:string};
export type ParsedPreview={version:string;storeId:string;storeCode:string;business:TemplateBusiness;allowedSkus:string[];rows:ParsedRow[];errors:string[];totalQty:number};
function text(cell:ExcelJS.Cell){const value=cell.value;if(value==null)return"";if(typeof value==="object"&&"text"in value)return String(value.text).trim();return String(value).trim()}
function integer(cell:ExcelJS.Cell){const raw=cell.value,value=typeof raw==="number"?raw:Number(text(cell));return Number.isSafeInteger(value)?value:Number.NaN}
function isoDate(cell:ExcelJS.Cell){if(cell.value instanceof Date&&!Number.isNaN(cell.value.getTime()))return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai"}).format(cell.value);const value=text(cell);return /^\d{4}-\d{2}-\d{2}$/.test(value)?value:""}
function formula(cell:ExcelJS.Cell){return typeof cell.value==="object"&&cell.value!==null&&"formula"in cell.value}
export async function parseOperationWorkbook(buffer:Buffer):Promise<ParsedPreview>{const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(buffer as unknown as ExcelJS.Buffer);const meta=workbook.getWorksheet("模板信息");if(!meta)throw new Error("缺少模板信息工作表，请重新下载模板。");const metadata=new Map<string,string>();meta.eachRow(row=>metadata.set(text(row.getCell(1)),text(row.getCell(2))));const business=z.enum(["arrival","outbound"]).parse(metadata.get("业务类型")),version=metadata.get("模板版本")??"";if(version!==TEMPLATE_VERSION)throw new Error("模板版本已过期，请重新下载模板。");const storeId=z.string().uuid().parse(metadata.get("店铺ID")),storeCode=metadata.get("店铺代码")??"",allowedSkus=(metadata.get("允许的商品SKU")??"").split("|").filter(Boolean),sheet=workbook.worksheets.find(item=>item.name!=="模板信息");if(!sheet)throw new Error("缺少业务工作表。");const rows:ParsedRow[]=[],errors:string[]=[];
 for(let n=6;n<=sheet.rowCount;n+=1){const row=sheet.getRow(n),sku=text(row.getCell(2));let empty=true;for(let c=1;c<=row.cellCount;c+=1){if(text(row.getCell(c))){empty=false;break}}if(!sku&&empty)continue;if(!sku){errors.push(`第 ${n} 行：商品SKU不能为空。`);continue}if(!allowedSkus.includes(sku))errors.push(`第 ${n} 行：SKU ${sku} 不属于此模板。`);row.eachCell({includeEmpty:false},cell=>{if(formula(cell)&&!(business==="arrival"&&Number(cell.col)===7))errors.push(`第 ${n} 行：输入列不允许公式。`)});const operation=text(row.getCell(1)),name=text(row.getCell(3));if(operation!==(business==="arrival"?"到仓待入":"出库"))errors.push(`第 ${n} 行：操作类型不正确。`);const businessDate=isoDate(row.getCell(business==="arrival"?8:5));if(!businessDate)errors.push(`第 ${n} 行：业务日期必须是有效日期。`);if(business==="arrival"){const units=integer(row.getCell(4)),cartons=integer(row.getCell(5)),loose=integer(row.getCell(6));if(!Number.isSafeInteger(units)||units<=0)errors.push(`第 ${n} 行：每箱件数无效。`);if(!Number.isSafeInteger(cartons)||cartons<0)errors.push(`第 ${n} 行：箱数必须是非负整数。`);if(!Number.isSafeInteger(loose)||loose<0||loose>=units)errors.push(`第 ${n} 行：尾数必须小于每箱件数。`);const quantity=units*cartons+loose;if(!Number.isSafeInteger(quantity)||quantity<=0)errors.push(`第 ${n} 行：总件数必须大于 0。`);const supplierCode=text(row.getCell(9));if(!supplierCode)errors.push(`第 ${n} 行：供应商代码不能为空。`);rows.push({row:n,sku,name,unitsPerCarton:units,cartons,loose,quantity,businessDate,supplierCode,note:text(row.getCell(10))})}else{const quantity=integer(row.getCell(4));if(!Number.isSafeInteger(quantity)||quantity<=0)errors.push(`第 ${n} 行：出库数量必须是正整数。`);rows.push({row:n,sku,name,quantity,businessDate,note:text(row.getCell(6))})}}
 if(!rows.length)errors.push("模板中没有可处理的数据行。");if(new Set(rows.map(row=>row.sku)).size!==rows.length)errors.push("同一个商品SKU不能重复出现。");return{version,storeId,storeCode,business,allowedSkus,rows,errors,totalQty:rows.reduce((sum,row)=>sum+(Number.isSafeInteger(row.quantity)?row.quantity:0),0)}}
