"use client";

import {useActionState,useState} from "react";
import {CheckCircle2,MinusCircle,Plus,Trash2} from "lucide-react";
import {adjustmentAction,outboundAction,receiptAction,type OperationState} from "./actions";
type Reason={code:string;label:string};type Product={id:string;sku:string;name:string;available:string;unitsPerCarton:number|null};type Pending={id:string;productId:string;sku:string;name:string;remaining:string;units:number;cartons:number;loose:number;supplier:string};
const initial:OperationState={};const box="h-10 rounded border border-[#ccd4cf] bg-white px-2";
function Feedback({state}:{state:OperationState}){return <>{state.error?<p role="alert" className="border-l-2 border-[#b94b35] bg-[#fbece7] p-3 text-sm text-[#8d3424]">{state.error}</p>:null}{state.success?<p role="status" className="border-l-2 border-[#0f7f6d] bg-[#e7f4ef] p-3 text-sm text-[#0a6254]">{state.success} 批次：{state.batchId}</p>:null}</>}

export function ReceiptForm({pending,reasons,keyValue,today}:{pending:Pending[];reasons:Reason[];keyValue:string;today:string}){
 const [state,action,busy]=useActionState(receiptAction,initial);const [rows,setRows]=useState(()=>new Map(pending.map(p=>[p.id,{selected:false,cartons:0,loose:0,reasonCode:"",note:""}])));const patch=(id:string,v:Record<string,unknown>)=>setRows(current=>{const next=new Map(current);next.set(id,{...next.get(id)!,...v});return next});const items=pending.filter(p=>rows.get(p.id)?.selected).map(p=>({pendingReceiptId:p.id,cartons:Number(rows.get(p.id)?.cartons)||0,loose:Number(rows.get(p.id)?.loose)||0,reasonCode:String(rows.get(p.id)?.reasonCode||""),note:String(rows.get(p.id)?.note||"")}));
 return <form action={action} className="grid gap-5"><input type="hidden" name="idempotencyKey" value={keyValue}/><input type="hidden" name="itemsJson" value={JSON.stringify(items)}/><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">业务日期<input className={box} type="date" name="businessDate" defaultValue={today}/></label><label className="grid gap-2 text-sm font-semibold">批次备注<input className={box} name="note"/></label></div><div className="overflow-x-auto border border-[#d8ded9]"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-[#f0f2ef]"><tr><th className="p-3">选择</th><th className="p-3">商品 / 供应商</th><th className="p-3">剩余待入</th><th className="p-3">实际箱数</th><th className="p-3">实际尾数</th><th className="p-3">差异原因</th><th className="p-3">备注</th></tr></thead><tbody>{pending.map(p=>{const r=rows.get(p.id)!;return <tr key={p.id} className="border-t border-[#e5e8e5]"><td className="p-3"><input aria-label={`选择 ${p.sku}`} type="checkbox" checked={r.selected} onChange={e=>patch(p.id,{selected:e.target.checked})}/></td><td className="p-3"><strong>{p.sku}</strong><span className="block text-[#68736f]">{p.name} · {p.supplier}</span></td><td className="p-3">{p.remaining} 件<span className="block text-[#68736f]">{p.units}/箱</span></td><td className="p-3"><input aria-label={`${p.sku} 实际箱数`} className={box+" w-24"} type="number" min="0" value={r.cartons} onChange={e=>patch(p.id,{cartons:Number(e.target.value)})}/></td><td className="p-3"><input aria-label={`${p.sku} 实际尾数`} className={box+" w-24"} type="number" min="0" max={p.units-1} value={r.loose} onChange={e=>patch(p.id,{loose:Number(e.target.value)})}/></td><td className="p-3"><select className={box} value={r.reasonCode} onChange={e=>patch(p.id,{reasonCode:e.target.value})}><option value="">无差异</option>{reasons.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></td><td className="p-3"><input className={box} value={r.note} onChange={e=>patch(p.id,{note:e.target.value})}/></td></tr>})}</tbody></table></div><Feedback state={state}/><div className="flex gap-3"><button name="mode" value="confirm" disabled={busy||items.length===0} className="flex h-11 items-center gap-2 rounded bg-[#0f7f6d] px-5 font-semibold text-white disabled:opacity-50"><CheckCircle2 size={17}/>确认实际入库</button><button name="mode" value="cancel" disabled={busy||items.length===0} className="flex h-11 items-center gap-2 rounded border border-[#a23f2d] px-5 font-semibold text-[#a23f2d] disabled:opacity-50"><MinusCircle size={17}/>取消剩余待入</button></div></form>
}

type StockRow={key:string;productId:string;quantity:number;reasonCode:string;note:string};
export function StockForm({mode,products,reasons,keyValue,today}:{mode:"outbound"|"adjustment";products:Product[];reasons:Reason[];keyValue:string;today:string}){
 const fn=mode==="outbound"?outboundAction:adjustmentAction;const [state,action,busy]=useActionState(fn,initial);const [rows,setRows]=useState<StockRow[]>([{key:"r1",productId:products[0]?.id??"",quantity:0,reasonCode:"",note:""}]);const patch=(key:string,v:Partial<StockRow>)=>setRows(cur=>cur.map(r=>r.key===key?{...r,...v}:r));const items=rows.map(r=>mode==="outbound"?{productId:r.productId,quantity:Number(r.quantity)||0,note:r.note}:{productId:r.productId,targetQty:Number(r.quantity)||0,reasonCode:r.reasonCode,note:r.note});
 return <form action={action} className="grid gap-5"><input type="hidden" name="idempotencyKey" value={keyValue}/><input type="hidden" name="itemsJson" value={JSON.stringify(items)}/><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">业务日期<input className={box} type="date" name="businessDate" defaultValue={today}/></label><label className="grid gap-2 text-sm font-semibold">批次备注<input className={box} name="note"/></label></div><div className="border border-[#d8ded9]"><div className={`grid ${mode==="adjustment"?"grid-cols-[1fr_150px_200px_1fr_50px]":"grid-cols-[1fr_160px_1fr_50px]"} gap-3 bg-[#f0f2ef] p-3 text-sm font-semibold`}><span>商品 SKU</span><span>{mode==="outbound"?"出库件数":"实盘目标数量"}</span>{mode==="adjustment"?<span>差异原因</span>:null}<span>备注</span><span/></div>{rows.map((r,i)=>{return <div key={r.key} className={`grid ${mode==="adjustment"?"grid-cols-[1fr_150px_200px_1fr_50px]":"grid-cols-[1fr_160px_1fr_50px]"} items-center gap-3 border-t border-[#e5e8e5] p-3`}><select className={box} value={r.productId} onChange={e=>patch(r.key,{productId:e.target.value})}>{products.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name} · 可用 {x.available}</option>)}</select><input aria-label={`第 ${i+1} 行数量`} className={box} type="number" min={mode==="outbound"?1:0} value={r.quantity} onChange={e=>patch(r.key,{quantity:Number(e.target.value)})}/>{mode==="adjustment"?<select className={box} value={r.reasonCode} onChange={e=>patch(r.key,{reasonCode:e.target.value})}><option value="">选择原因</option>{reasons.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select>:null}<input className={box} value={r.note} onChange={e=>patch(r.key,{note:e.target.value})} placeholder={mode==="adjustment"?"必填具体说明":"可选"}/><button type="button" disabled={rows.length===1} onClick={()=>setRows(cur=>cur.filter(x=>x.key!==r.key))} className="text-[#a23f2d] disabled:opacity-30"><Trash2 size={16}/></button></div>})}</div><button type="button" onClick={()=>setRows(cur=>[...cur,{key:crypto.randomUUID(),productId:products[0]?.id??"",quantity:0,reasonCode:"",note:""}])} className="flex h-10 w-fit items-center gap-2 rounded border border-[#0f7f6d] px-4 text-sm font-semibold text-[#0f7f6d]"><Plus size={16}/>增加商品</button><Feedback state={state}/><button disabled={busy||products.length===0} className="h-11 w-fit rounded bg-[#0f7f6d] px-6 font-semibold text-white disabled:opacity-50">{busy?"原子入账中…":mode==="outbound"?"确认整批出库":"确认库存纠错"}</button></form>
}
